// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128221005_AddFeaturesBcraToHistorialScoring")]
    partial class AddFeaturesBcraToHistorialScoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Backend.Domain.Entities.Client.AjusteScoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("HistorialScoringId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HistorialScoringId")
                        .HasDatabaseName("IX_AjustesScoring_HistorialScoringId");

                    b.ToTable("AjustesScoring", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Client.AlertaScoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HistorialScoringId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HistorialScoringId")
                        .HasDatabaseName("IX_AlertasScoring_HistorialScoringId");

                    b.ToTable("AlertasScoring", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Client.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cuil")
                        .IsUnique()
                        .HasDatabaseName("IX_Clientes_Cuil_Unique");

                    b.HasIndex("EstaActivo")
                        .HasDatabaseName("IX_Clientes_EstaActivo");

                    b.HasIndex("EstaActivo", "CreadoEn")
                        .HasDatabaseName("IX_Clientes_EstaActivo_CreadoEn");

                    b.HasIndex("Nombre", "Apellido")
                        .HasDatabaseName("IX_Clientes_NombreApellido");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Client.HistorialScoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntajeBase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntajeFinal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SinEvidenciaCrediticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_HistorialesScoring_ClienteId");

                    b.HasIndex("ClienteId", "CalculadoEn")
                        .HasDatabaseName("IX_HistorialesScoring_Cliente_Fecha");

                    b.ToTable("HistorialesScoring", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Scoring.ReglaAjuste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ajuste")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("TipoAjuste")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ValorMaximo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorMinimo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoAjuste", "EstaActivo")
                        .HasDatabaseName("IX_ReglasAjustes_Tipo_Activa");

                    b.HasIndex("TipoAjuste", "ValorMinimo", "ValorMaximo")
                        .HasDatabaseName("IX_ReglasAjustes_Tipo_Rango");

                    b.ToTable("ReglasAjustes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ajuste = 0,
                            Codigo = "PEOR_SIT_24M_NORMAL",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Sin deterioro histórico",
                            EstaActivo = true,
                            TipoAjuste = 1,
                            ValorMaximo = 1,
                            ValorMinimo = 1
                        },
                        new
                        {
                            Id = 2,
                            Ajuste = -5,
                            Codigo = "PEOR_SIT_24M_NIVEL_2",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Riesgo bajo histórico detectado",
                            EstaActivo = true,
                            TipoAjuste = 1,
                            ValorMaximo = 2,
                            ValorMinimo = 2
                        },
                        new
                        {
                            Id = 3,
                            Ajuste = -12,
                            Codigo = "PEOR_SIT_24M_NIVEL_3",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Dificultades históricas detectadas",
                            EstaActivo = true,
                            TipoAjuste = 1,
                            ValorMaximo = 3,
                            ValorMinimo = 3
                        },
                        new
                        {
                            Id = 4,
                            Ajuste = -20,
                            Codigo = "PEOR_SIT_24M_NIVEL_4",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Situación severa histórica",
                            EstaActivo = true,
                            TipoAjuste = 1,
                            ValorMaximo = 4,
                            ValorMinimo = 4
                        },
                        new
                        {
                            Id = 5,
                            Ajuste = -35,
                            Codigo = "PEOR_SIT_24M_CRITICA",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Situación crítica en historial",
                            EstaActivo = true,
                            TipoAjuste = 1,
                            ValorMinimo = 5
                        },
                        new
                        {
                            Id = 6,
                            Ajuste = 0,
                            Codigo = "MESES_MORA_NINGUNO",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Sin períodos de mora",
                            EstaActivo = true,
                            TipoAjuste = 2,
                            ValorMaximo = 0,
                            ValorMinimo = 0
                        },
                        new
                        {
                            Id = 7,
                            Ajuste = -5,
                            Codigo = "MESES_MORA_OCASIONAL",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "1-2 meses en mora",
                            EstaActivo = true,
                            TipoAjuste = 2,
                            ValorMaximo = 2,
                            ValorMinimo = 1
                        },
                        new
                        {
                            Id = 8,
                            Ajuste = -12,
                            Codigo = "MESES_MORA_FRECUENTE",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "3-5 meses en mora",
                            EstaActivo = true,
                            TipoAjuste = 2,
                            ValorMaximo = 5,
                            ValorMinimo = 3
                        },
                        new
                        {
                            Id = 9,
                            Ajuste = -20,
                            Codigo = "MESES_MORA_PERSISTENTE",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "6-10 meses en mora",
                            EstaActivo = true,
                            TipoAjuste = 2,
                            ValorMaximo = 10,
                            ValorMinimo = 6
                        },
                        new
                        {
                            Id = 10,
                            Ajuste = -30,
                            Codigo = "MESES_MORA_CRONICA",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Más de 10 meses en mora",
                            EstaActivo = true,
                            TipoAjuste = 2,
                            ValorMinimo = 11
                        },
                        new
                        {
                            Id = 11,
                            Ajuste = -20,
                            Codigo = "MORA_MUY_RECIENTE",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Mora en los últimos 2 meses",
                            EstaActivo = true,
                            TipoAjuste = 3,
                            ValorMaximo = 2,
                            ValorMinimo = 0
                        },
                        new
                        {
                            Id = 12,
                            Ajuste = -12,
                            Codigo = "MORA_RECIENTE",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Mora hace 3-5 meses",
                            EstaActivo = true,
                            TipoAjuste = 3,
                            ValorMaximo = 5,
                            ValorMinimo = 3
                        },
                        new
                        {
                            Id = 13,
                            Ajuste = -6,
                            Codigo = "MORA_MODERADA",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Mora hace 6-11 meses",
                            EstaActivo = true,
                            TipoAjuste = 3,
                            ValorMaximo = 11,
                            ValorMinimo = 6
                        },
                        new
                        {
                            Id = 14,
                            Ajuste = 0,
                            Codigo = "MORA_ANTIGUA",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Mora hace más de 12 meses",
                            EstaActivo = true,
                            TipoAjuste = 3,
                            ValorMinimo = 12
                        },
                        new
                        {
                            Id = 15,
                            Ajuste = 0,
                            Codigo = "ENTIDADES_BAJA",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "0-1 entidades",
                            EstaActivo = true,
                            TipoAjuste = 4,
                            ValorMaximo = 1,
                            ValorMinimo = 0
                        },
                        new
                        {
                            Id = 16,
                            Ajuste = -4,
                            Codigo = "ENTIDADES_MEDIA",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "2-3 entidades",
                            EstaActivo = true,
                            TipoAjuste = 4,
                            ValorMaximo = 3,
                            ValorMinimo = 2
                        },
                        new
                        {
                            Id = 17,
                            Ajuste = -8,
                            Codigo = "ENTIDADES_ALTA",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "4-6 entidades",
                            EstaActivo = true,
                            TipoAjuste = 4,
                            ValorMaximo = 6,
                            ValorMinimo = 4
                        },
                        new
                        {
                            Id = 18,
                            Ajuste = -12,
                            Codigo = "ENTIDADES_MUY_ALTA",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Más de 6 entidades",
                            EstaActivo = true,
                            TipoAjuste = 4,
                            ValorMinimo = 7
                        },
                        new
                        {
                            Id = 19,
                            Ajuste = 0,
                            Codigo = "CHEQUES_NINGUNO",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Sin cheques rechazados",
                            EstaActivo = true,
                            TipoAjuste = 5,
                            ValorMaximo = 0,
                            ValorMinimo = 0
                        },
                        new
                        {
                            Id = 20,
                            Ajuste = -8,
                            Codigo = "CHEQUES_UNO",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "1 cheque rechazado",
                            EstaActivo = true,
                            TipoAjuste = 5,
                            ValorMaximo = 1,
                            ValorMinimo = 1
                        },
                        new
                        {
                            Id = 21,
                            Ajuste = -15,
                            Codigo = "CHEQUES_DOS",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "2 cheques rechazados",
                            EstaActivo = true,
                            TipoAjuste = 5,
                            ValorMaximo = 2,
                            ValorMinimo = 2
                        },
                        new
                        {
                            Id = 22,
                            Ajuste = -30,
                            Codigo = "CHEQUES_MULTIPLES",
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "3 o más cheques rechazados",
                            EstaActivo = true,
                            TipoAjuste = 5,
                            ValorMinimo = 3
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.Scoring.ReglaScoreBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("ScoreBase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Situacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Situacion", "EstaActivo")
                        .IsUnique()
                        .HasDatabaseName("IX_ReglasScoreBase_Situacion_Activa")
                        .HasFilter("EstaActivo = 1");

                    b.ToTable("ReglasScoreBase", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstaActivo = true,
                            ScoreBase = 80,
                            Situacion = 1
                        },
                        new
                        {
                            Id = 2,
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstaActivo = true,
                            ScoreBase = 55,
                            Situacion = 2
                        },
                        new
                        {
                            Id = 3,
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstaActivo = true,
                            ScoreBase = 35,
                            Situacion = 3
                        },
                        new
                        {
                            Id = 4,
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstaActivo = true,
                            ScoreBase = 15,
                            Situacion = 4
                        },
                        new
                        {
                            Id = 5,
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstaActivo = true,
                            ScoreBase = 0,
                            Situacion = 5
                        },
                        new
                        {
                            Id = 6,
                            CreadoEn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstaActivo = true,
                            ScoreBase = 0,
                            Situacion = 6
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.Client.AjusteScoring", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Client.HistorialScoring", "HistorialScoring")
                        .WithMany("Ajustes")
                        .HasForeignKey("HistorialScoringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistorialScoring");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Client.AlertaScoring", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Client.HistorialScoring", "HistorialScoring")
                        .WithMany("Alertas")
                        .HasForeignKey("HistorialScoringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistorialScoring");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Client.Cliente", b =>
                {
                    b.OwnsOne("Backend.Domain.Entities.Client.Direccion", "Domicilio", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Domicilio_Calle");

                            b1.Property<string>("Localidad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Domicilio_Localidad");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Domicilio_Provincia");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Domicilio")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Client.HistorialScoring", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Client.Cliente", "Cliente")
                        .WithMany("HistorialesScoring")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Backend.Domain.Entities.Client.FeaturesBcra", "FeaturesBcra", b1 =>
                        {
                            b1.Property<int>("HistorialScoringId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CantidadEntidadesActual")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0)
                                .HasColumnName("CantidadEntidadesActual");

                            b1.Property<int>("ChequesEventos12m")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0)
                                .HasColumnName("ChequesEventos12m");

                            b1.Property<int>("MaxSituacionActual")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0)
                                .HasColumnName("MaxSituacionActual");

                            b1.Property<int>("MesesMora24m")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0)
                                .HasColumnName("MesesMora24m");

                            b1.Property<int>("PeorSituacion24m")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0)
                                .HasColumnName("PeorSituacion24m");

                            b1.Property<int>("RecenciaMora")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0)
                                .HasColumnName("RecenciaMora");

                            b1.HasKey("HistorialScoringId");

                            b1.ToTable("HistorialesScoring");

                            b1.WithOwner()
                                .HasForeignKey("HistorialScoringId");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("FeaturesBcra");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Client.Cliente", b =>
                {
                    b.Navigation("HistorialesScoring");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Client.HistorialScoring", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
