// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable
namespace Backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109211551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.AjusteScoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("HistorialScoringId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasDatabaseName("IX_AjustesScoring_Codigo");

                    b.HasIndex("HistorialScoringId")
                        .HasDatabaseName("IX_AjustesScoring_HistorialScoringId");

                    b.ToTable("AjustesScoring", (string)null);
                });

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.AlertaScoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HistorialScoringId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HistorialScoringId")
                        .HasDatabaseName("IX_AlertasScoring_HistorialScoringId");

                    b.ToTable("AlertasScoring", (string)null);
                });

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cuil")
                        .IsUnique()
                        .HasDatabaseName("IX_Clientes_Cuil_Unique");

                    b.HasIndex("EstaActivo")
                        .HasDatabaseName("IX_Clientes_EstaActivo");

                    b.HasIndex("EstaActivo", "CreadoEn")
                        .HasDatabaseName("IX_Clientes_EstaActivo_CreadoEn");

                    b.HasIndex("Nombre", "Apellido")
                        .HasDatabaseName("IX_Clientes_NombreApellido");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.HistorialScoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculadoEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntajeBase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntajeFinal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SinEvidenciaCrediticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_HistorialesScoring_ClienteId");

                    b.HasIndex("ClienteId", "CalculadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_HistorialesScoring_ClienteId_CalculadoEn_Desc");

                    b.ToTable("HistorialesScoring", (string)null);
                });

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.AjusteScoring", b =>
                {
                    b.HasOne("Backend.WebAPI.Hades.Models.Client.HistorialScoring", "HistorialScoring")
                        .WithMany("Ajustes")
                        .HasForeignKey("HistorialScoringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistorialScoring");
                });

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.AlertaScoring", b =>
                {
                    b.HasOne("Backend.WebAPI.Hades.Models.Client.HistorialScoring", "HistorialScoring")
                        .WithMany("Alertas")
                        .HasForeignKey("HistorialScoringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistorialScoring");
                });

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.Cliente", b =>
                {
                    b.OwnsOne("Backend.WebAPI.Hades.Models.Client.Direccion", "Domicilio", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Domicilio_Calle");

                            b1.Property<string>("Localidad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Domicilio_Localidad");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Domicilio_Provincia");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Domicilio")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.HistorialScoring", b =>
                {
                    b.HasOne("Backend.WebAPI.Hades.Models.Client.Cliente", "Cliente")
                        .WithMany("HistorialesScoring")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.Cliente", b =>
                {
                    b.Navigation("HistorialesScoring");
                });

            modelBuilder.Entity("Backend.WebAPI.Hades.Models.Client.HistorialScoring", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
